export type AssetType = {
  dataFilter: any
  fullPath: string
  idPath: any
  iconType: string
  isFlagged: boolean
  iconTypeValue: any
  isWcoIntegrated: boolean
  permissionList: string
  hasCSharpInput: boolean
  id: number
  taskCount: number
  error_code: number
  branchId: number
  label: string
  type: number
  folder_id: number
  workflow_id: number
  workflow_step: number
  version_id: number
  template_version_id: number
  status_user_id: number
  status: number
  status_date: string
  owner_user_id: number
  creator_user_id: number
  storage_id: any
  extension: string
  create_date: string
  modified_user_id: number
  modified_date: string
  checkout_user_id: number
  checkout_date: string
  error_msg: any
  size: number
  template_id: number
  template_label: string
  acl_id: number
  change_date: string
  change_user_id: number
  child_id: number
  base_model_id: number
  model_id: any
  model_name: string
  deploy_id: number
  is_deleted: any
  is_hidden: any
  publish_date: string
  publish_dependencies_date: string
  publish_user_id: number
  template_language: number
  subtype: number
  statusName: string
  statusColor: string
  ownedBy: any
  createdBy: string
  modifiedBy: string
  lastPublishedBy: string
  statusChangedBy: string
  changedBy: string
  checkedOutBy: string
  templateSubType: number
  isQueued: boolean
  hasPeriodicSchedule: boolean
  hasWorkflowSchedule: boolean
  approvedWorkflowFilters: number[]
  extraId: any
};
